# tasks file for ufw
---
- include: install.yml
  tags:
    - configuration
    - ufw
    - ufw-install

- include: configure.yml
  tags:
    - configuration
    - ufw
    - ufw-configure

- name: start and enable service
  ufw:
    state: enabled
  tags:
    - configuration
    - ufw
    - ufw-start-enable-service
